CREATE TABLE ADDRESS(
    ADDRESS_ID BIGINT NOT NULL  AUTO_INCREMENT,
    ADDRESS_NAME VARCHAR (200),
    PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE CITY(
    CITY_ID BIGINT NOT NULL  AUTO_INCREMENT,
    CITY_NAME VARCHAR (200),
    ADDRESS_ID BIGINT,
    PRIMARY KEY(CITY_ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE COUNTRY(
     COUNTRY_ID BIGINT NOT NULL  AUTO_INCREMENT,
     COUNTRY_NAME VARCHAR (200),
     CITY_ID BIGINT,
     PRIMARY KEY (COUNTRY_ID),
     FOREIGN KEY (CITY_ID) REFERENCES CITY (CITY_ID)
)

CREATE  TABLE SERVICE_DIRECTORY(
     SERVICE_DIRECTORY_ID BIGINT NOT NULL  AUTO_INCREMENT,
     SERVICE_DIRECTORY_NAME VARCHAR (200),
     PRIMARY KEY (SERVICE_DIRECTORY_ID)
)

CREATE TABLE SERVICE_STATION(
    SERVICE_STATION_ID BIGINT NOT NULL  AUTO_INCREMENT,
    SERVICE_STATION_NAME VARCHAR (200),
    COUNTRY_ID BIGINT,
    SERVICE_DIRECTORY_ID BIGINT,
    PRIMARY KEY (SERVICE_STATION_ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
    FOREIGN KEY (SERVICE_DIRECTORY_ID) REFERENCES  SERVICE_DIRECTORY (SERVICE_DIRECTORY_ID)
);