INSERT INTO COUNTRY (COUNTRY_NAME) VALUE ('РОССИЯ');
INSERT INTO CITY (CITY_NAME,ADDRESS_ID) VALUES ('ТОМСК',1);
INSERT INTO CITY (CITY_NAME,ADDRESS_ID) VALUES ('МОСКВА',1);
INSERT INTO CITY (CITY_NAME,ADDRESS_ID) VALUES ('БАРНАУЛ',1);
INSERT INTO ADDRESS (ADDRESS_NAME,CITY_ID) VALUES ('УЛ. ЛЕНИНА ДОМ 26',1);
INSERT INTO ADDRESS (ADDRESS_NAME,CITY_ID) VALUES ('УЛ. ПОПОВА ДОМ 32',2);
INSERT INTO ADDRESS (ADDRESS_NAME,CITY_ID) VALUES ('УЛ. ПУШКИНА ДОМ 57',3);
INSERT INTO SERVICE_DIRECTORY (SERVICE_DIRECTORY_NAME) VALUE ('ОФОРМЛЕНИЕ ДОКУМЕНТОВ');
INSERT INTO SERVICE_DIRECTORY (SERVICE_DIRECTORY_NAME) VALUE ('ВЫДАЧА СПРАВОК');
INSERT INTO SERVICE_DIRECTORY (SERVICE_DIRECTORY_NAME) VALUE ('КОНСУЛЬТАЦИЯ ПО ПРОДУКТАМ');
INSERT INTO SERVICE_STATION (SERVICE_STATION_NAME,ADDRESS_ID) VALUES ('SERVICE-1',1);
INSERT INTO SERVICE_STATION (SERVICE_STATION_NAME,ADDRESS_ID) VALUES ('SERVICE-2',1);
INSERT INTO SERVICE_STATION (SERVICE_STATION_NAME,ADDRESS_ID) VALUES ('SERVICE-3',3);
INSERT INTO SERVICE_STATION (SERVICE_STATION_NAME,ADDRESS_ID) VALUES ('SERVICE-4',3);
INSERT INTO SERVICE_DIRECTORY_SERVICE_STATION (SERVICE_STATION_ID,SERVICE_DIRECTORY_ID) VALUES (1,2)
INSERT INTO SERVICE_DIRECTORY_SERVICE_STATION (SERVICE_STATION_ID,SERVICE_DIRECTORY_ID) VALUES (2,3)
INSERT INTO SERVICE_DIRECTORY_SERVICE_STATION (SERVICE_STATION_ID,SERVICE_DIRECTORY_ID) VALUES (3,3)
INSERT INTO SERVICE_DIRECTORY_SERVICE_STATION (SERVICE_STATION_ID,SERVICE_DIRECTORY_ID) VALUES (4,1)